name = "haprial-comments"
main = "worker.js"
compatibility_date = "2024-12-01"

# Custom domain
routes = [
  { pattern = "comments.pluslogic.eu.org/*", zone_name = "pluslogic.eu.org" }
]

# KV binding
[[kv_namespaces]]
binding = "COMMENTS"
id = "6b430b3e18c7463e967fe0effbd7e2eb"

# Environment variables
# [vars]
# ADMIN_SECRET = "<your-admin-secret>"
# ALLOWED_ORIGINS = "https://pluslogic.eu.org"
